// Task seed data — the "Creative / Micro" tiers from the strategy doc.
export const TASKS = [
  {
    id: 'palo-alto',
    title: 'Rep Whop in Palo Alto',
    brand: 'Whop',
    emoji: '📍',
    payout: 25,
    time: '~20 min',
    tier: 'Creative',
    slots: 12,
    blurb: 'Film a quick street clip hyping Whop and post it publicly.',
    steps: [
      'Head to University Ave in Palo Alto',
      'Film a 15 to 30 second video saying “Whop is an awesome company”',
      'Post it to your TikTok, IG Story, or X',
      'Paste the post link below to submit',
    ],
    rules: ['Face visible', 'Says “Whop” out loud', 'Public post', 'Min 15 seconds'],
  },
  {
    id: 'google-review',
    title: 'Drop a 5★ Google review',
    brand: 'Whop',
    emoji: '⭐',
    payout: 8,
    time: '~5 min',
    tier: 'Micro',
    slots: 40,
    blurb: 'Leave an honest review on the Whop Google listing.',
    steps: [
      'Open the Whop Google Business listing',
      'Write 2 to 3 honest sentences about your experience',
      'Submit the review',
      'Screenshot it and upload below',
    ],
    rules: ['Real account', '5★ + written text', 'Screenshot as proof'],
  },
  {
    id: 'story-share',
    title: 'Share Whop on your story',
    brand: 'Whop',
    emoji: '📲',
    payout: 12,
    time: '~3 min',
    tier: 'Micro',
    slots: 25,
    blurb: 'Post the Whop link to your IG / Snap story for 24h.',
    steps: [
      'Add the Whop link sticker to your story',
      'Tag @whop',
      'Keep it up for 24 hours',
      'Upload a screenshot below',
    ],
    rules: ['Public story', 'Link sticker visible', '500+ followers'],
  },
  {
    id: 'whop-meme',
    title: 'Make a meme about Whop',
    brand: 'Whop',
    emoji: '😂',
    payout: 15,
    time: '~15 min',
    tier: 'Creative',
    slots: 18,
    blurb: 'Original meme about making money on Whop. Funny = approved.',
    steps: [
      'Create an original meme about earning on Whop',
      'Post it to X or IG',
      'Tag @whop',
      'Paste the link below',
    ],
    rules: ['Original', 'On-brand', 'Public post'],
  },
  {
    id: 'reply-threads',
    title: 'Reply to 5 side-hustle posts',
    brand: 'Whop',
    emoji: '💬',
    payout: 10,
    time: '~10 min',
    tier: 'Micro',
    slots: 30,
    blurb: 'Helpfully mention Whop on 5 relevant X threads.',
    steps: [
      'Find 5 posts about side hustles / making money online',
      'Reply genuinely, mentioning Whop where it fits',
      'Screenshot all 5 replies',
      'Upload below',
    ],
    rules: ['Genuine replies', 'No spam', '5 different threads'],
  },
]
